language: node_js

node_js:
  - stable

services:
  - couchdb

before_script:
  - git config --global user.email "foo@bar.com"
  - git config --global user.name "Foo Bar"
  - npm install -g jscs
  - curl -X PUT http://127.0.0.1:5984/travis-node-demo
  - curl -X GET http://127.0.0.1:5984/_all_dbs

script:
  - jscs src

deploy:
  provider: npm
  email: foo@bar.com
  api_key:
    secure: {Insert deploy key here}
  on:
    tags: true
    repo: tejasrsuthar/travis-node-example
    all_branches: true

notifications:
  email:
    recipients:
      - tejas.suthar@flinnt.com
    on_success: always
    on_failure: always

  slack:
    rooms:
      - secure: {Insert Slack key here}
    on_success: always
    on_failure: always
    on_start: always
